# Generated by Django 3.0.6 on 2020-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
