# Generated by Django 3.0.6 on 2020-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0002_auto_20200521_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
